### PR TITLE
force correct debug type

### PR DESCRIPTION
**Pull request by SimonCropp**
by including a targets file for all consumers

### CODE REVIEW

**Comment by egil** [comment]
Thanks a lot for this. This is some new msbuild magic to me :)

Will this also work in the case where another lib is using this, e.g. bUnit, and that bUnit is being added to a test project?

**Comment by SimonCropp** [comment]
u may need to tweak the package ref. push this to nuget and i will have a look at bunit

**Comment by egil** [comment]
OK. Ill push a package to githubs package repo tonight so we can test, without pushing to nuget.

**Comment by egil** [comment]
So sorry @SimonCropp for completely forgetting about this. Life got in the way.

**Comment by egil** [comment]
A new version should be appearing on https://www.nuget.org/packages/SourceFileFinder/ in a little bit.

**Pull request merged**
